version: "3.9"
x-common:
  &x-common
  build:
    context: .
    dockerfile: Dockerfile
  init: true
  environment:
    DEV_HOSTS: d1,d2,d3,d4
  volumes:
    - ..:/workspaces/ucx-practice:cached
    - spack:/home/vscode/.cache/spack
    - dot-spack:/home/vscode/.spack
  shm_size: '5gb'
  ulimits:
      memlock: -1
  cap_add:
    - SYS_PTRACE
  security_opt:
    - seccomp:unconfined
  privileged: true
  command: >
    bash -c "sudo service ssh restart && sleep infinity"

services:
  dev1:
    <<: *x-common
    hostname: d1
    container_name: ucx_d1
  dev2:
    <<: *x-common
    hostname: d2
    container_name: ucx_d2
  dev3:
    <<: *x-common
    hostname: d3
    container_name: ucx_d3
  dev4:
    <<: *x-common
    hostname: d4
    container_name: ucx_d4

volumes:
  spack:
    external: true
  dot-spack:
    external: true
